### ISSUE TITLE
Different tint colors for selected and unselected tabs

### ISSUE THREAD

**Issue by EmpiteShehan** [hoang8f/android-segmented-control#25]
How to set different tint colors for selected and unselected tabs
![img_0193](https://cloud.githubusercontent.com/assets/11847268/7066678/94a3a52a-dee2-11e4-92fa-2a8c61b402b0.PNG)

**Comment by hoang8f** [comment]
@EmpiteShehan use `setTintColor` method
for example:
```
SegmentedGroup segmented2 = (SegmentedGroup) rootView.findViewById(R.id.segmented2);
segmented2.setTintColor(Color.DKGRAY);

SegmentedGroup segmented3 = (SegmentedGroup) rootView.findViewById(R.id.segmented3);
segmented3.setTintColor(Color.parseColor("#FFD0FF3C"), Color.parseColor("#FF7B07B2"));

SegmentedGroup segmented4 = (SegmentedGroup) rootView.findViewById(R.id.segmented4);
segmented4.setTintColor(getResources().getColor(R.color.radio_button_selected_color));
```

**Comment by EmpiteShehan** [comment]
Thank you  :)

**Comment by EmpiteShehan** [comment]
This doesn't work. I want separate tint colors for selected and unselected tabs . I don't want to add separate SegmentedGroups.

**Comment by hoang8f** [comment]
@EmpiteShehan Sorry, I misunderstood.
My library doesn't support your requirement.
You can pull my source and customize with your style.
I think you should do some change on this method `private void updateBackground(View view) {`

**Comment by EmpiteShehan** [comment]
thanks for the help :)
